### ISSUE TITLE
Exception when deleting check list item

### ISSUE THREAD

**Issue by ramu2514** [federicoiosue/checklistview#13]
03-21 23:01:38.040 28123-28123/com.avrapps.note E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.avrapps.note, PID: 28123
                                                                  java.lang.NullPointerException: Attempt to invoke interface method 'void it.feio.android.checklistview.interfaces.CheckListChangedListener.onCheckListChanged()' on a null object reference
                                                                      at it.feio.android.checklistview.models.CheckListView.onLineDeleted(CheckListView.java:395)
                                                                      at it.feio.android.checklistview.models.CheckListViewItem$1.run(CheckListViewItem.java:246)
                                                                      at android.os.Handler.handleCallback(Handler.java:815)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                      at android.os.Looper.loop(Looper.java:194)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5763)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by ramu2514** [comment]
Issue got fixed by adding below lines to code
            CheckListChangedListener listener=new CheckListChangedListener() {
                @Override
                public void onCheckListChanged() {
                }
            };
            mChecklistManager.setCheckListChangedListener(listener);
