### ISSUE TITLE
FrameLayout cannot be casted to ScrollView Error

### ISSUE THREAD

**Issue by MidsizeMango** [federicoiosue/checklistview#16]
When I try to drag the Checklist Items, it gives me this error in logs and App Force Stops.

` java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.widget.ScrollView
                                                                               at it.feio.android.checklistview.dragging.ChecklistViewItemOnDragListener.onDrag(ChecklistViewItemOnDragListener.java:34)
                                                                               at android.view.View.dispatchDragEvent(View.java:19699)
                                                                               at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1532)
                                                                               at it.feio.android.checklistview.models.CheckListView.dispatchDragEvent(CheckListView.java:407)
                                                                               at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1469)
                                                                               at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)
                                                                               at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)
                                                                               at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)
                                                                               at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)
                                                                               at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)
                                                                               at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)
                                                                               at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)
                                                                               at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5290)
                                                                               at android.view.ViewRootImpl.-wrap6(ViewRootImpl.java)
                                                                               at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3465)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

**Comment by federicoiosue** [comment]
Would be usef to have a context where this happens. We're talking about an app
I developed (Checklistview Demo, Omni Notes) or you're using the library into
your own app?![](https://link.nylas.com/open/7vjrx0c0tcxineb9xy9cu8dii/local-
8170567b-2da1)

On giu 7 2016, at 9:48 am, Prasad Shirvandkar &lt;notifications@github.com&gt;
wrote:  

> When I try to drag the Checklist Items, it gives me this error in logs and
App Force Stops.

>

> java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to
android.widget.ScrollView  
at it.feio.android.checklistview.dragging.ChecklistViewItemOnDragListener.onDr
ag(ChecklistViewItemOnDragListener.java:34)  
at android.view.View.dispatchDragEvent(View.java:19699)  
at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1532)  
at it.feio.android.checklistview.models.CheckListView.dispatchDragEvent(CheckL
istView.java:407)  
at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1469)  
at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)  
at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)  
at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)  
at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)  
at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)  
at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)  
at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1481)  
at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5290)  
at android.view.ViewRootImpl.-wrap6(ViewRootImpl.java)  
at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3
465)  
at android.os.Handler.dispatchMessage(Handler.java:102)  
at android.os.Looper.loop(Looper.java:148)  
at android.app.ActivityThread.main(ActivityThread.java:5422)  
at java.lang.reflect.Method.invoke(Native Method)  
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:
726)  
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)  

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly, [view it on
GitHub](https://github.com/federicoiosue/checklistview/issues/16), or [mute
the thread](https://github.com/notifications/unsubscribe/AAduwMhMnTwrxQeIxjgWC
UJV15eMPIIFks5qJSJLgaJpZM4Ivpmk).![](https://github.com/notifications/beacon/A
AduwCI_WTIGUry21RfeNtOSFURNftXIks5qJSJLgaJpZM4Ivpmk.gif)

**Comment by MidsizeMango** [comment]
@federicoiosue I am using library into my app

**Comment by federicoiosue** [comment]
Looking to the code would be
useful![](https://link.nylas.com/open/7vjrx0c0tcxineb9xy9cu8dii/local-
8c8cc4c0-c756)

On giu 11 2016, at 8:42 pm, Prasad Shirvandkar
&lt;notifications@github.com&gt; wrote:  

> [@federicoiosue](https://github.com/federicoiosue) I am using library into
my app

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly, [view it on GitHub](https://github.com/federicoi
osue/checklistview/issues/16#issuecomment-225382629), or [mute the thread](htt
ps://github.com/notifications/unsubscribe/AAduwHM5-8D798xyCYkatIZshhRhb9_bks5q
KwGIgaJpZM4Ivpmk).![](https://github.com/notifications/beacon/AAduwCWya0XMIuJ_
XVS1-xJy0joSDL-xks5qKwGIgaJpZM4Ivpmk.gif)

**Comment by MidsizeMango** [comment]
@federicoiosue The Link is not opening

**Comment by federicoiosue** [comment]
Without a context I can't help you, give a look to the demo app to see what
eventually had happened.

It also depends on WHEN you get the error (talking about drag&drop action)

Il dom 12 giu 2016, 19:42 Prasad Shirvandkar <notifications@github.com> ha
scritto:
