### ISSUE TITLE
App crash when drag checklist item 

### ISSUE THREAD

**Issue by vishalvala** [federicoiosue/CheckListView#24]
I am using library versio 3.2.1. when i drag any item it gives me error like below:

2021-08-14 10:00:10.929 7261-7261/com.example.notes E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.notes, PID: 7261
    java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.widget.ScrollView
        at it.feio.android.checklistview.dragging.ChecklistViewItemOnDragListener.onDrag(ChecklistViewItemOnDragListener.java:38)
        at it.feio.android.checklistview.models.CheckListViewItem.manageDragEvents(CheckListViewItem.java:389)
        at it.feio.android.checklistview.models.CheckListViewItem.access$200(CheckListViewItem.java:33)
        at it.feio.android.checklistview.models.CheckListViewItem$3.onDrag(CheckListViewItem.java:379)
        at android.view.View.callDragEventHandler(View.java:25627)
        at android.view.View.dispatchDragEvent(View.java:25618)
        at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
        at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
        at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
        at it.feio.android.checklistview.models.CheckListView.dispatchDragEvent(CheckListView.java:422)
        at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
        at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
        at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
        at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
        at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
        at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
        at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
        at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
        at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:6724)
        at android.view.ViewRootImpl.access$1200(ViewRootImpl.java:142)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4587)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by federicoiosue** [comment]
Hi there,

Does this happen on a specific Android version? Known problems exist on Android 7 for example.
